from django.core.urlresolvers import reverse
from django.db import models


class Window(models.Model):
    # TODO: Refactor this to inherit model from fotutils.models.FotModel, also for Var and Device models
    title = models.CharField(max_length=100)
    slug = models.SlugField(unique=True,
        help_text="Url friendly title. Leaving it in blank will be autogenerated, but if defined must be unique."
    )
    # TODO: Add image field for background
    description = models.CharField(max_length=256, blank=True)

    def get_absolute_url(self):
        return reverse('window_details', args=(self.slug,))