# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 16:19
from __future__ import unicode_literals

from django.contrib.auth.models import Group
from django.db import migrations


def add_default_groups(apps, schema_editor):
    """Create default groups for users"""
    Group.objects.create(name="assistants")
    Group.objects.create(name="operators")


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_default_groups),
    ]
