# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='slug',
            field=models.SlugField(help_text=b'Url friendly name. Leaving it in blank will be autogenerated, but if defined must be unique.', unique=True, max_length=25),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='var',
            name='slug',
            field=models.SlugField(help_text=b'Url friendly name. Leaving it in blank will be autogenerated, but if defined must be unique.', unique=True, max_length=25),
            preserve_default=True,
        ),
    ]
